
name: Java CI with Maven

on:
  push:
    branches: [ main ]

env:
  TKE_IMAGE_URL: deccr.ccs.tencentyun.com/myfana2022/backend
  TKE_REGION: eu-frankfurt
  TKE_CLUSTER_ID: cls-oh2fi8hk
  TKE_CLUSTER_IP: https://43.131.7.42:443
  DEPLOYMENT_NAME: sbdemo

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
#      - name: BuildDockerImage
#        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      - name: Build Docker Image
        run:
          docker build -t ${TKE_IMAGE_URL}:${GITHUB_SHA} .

      - name: Login TKE Registry
        run: |
          docker login -u ${{ secrets.TENCENT_CLOUD_ACCOUNT_ID }} -p '${{ secrets.TKE_REGISTRY_PASSWORD }}' ${TKE_IMAGE_URL}
#          docker login deccr.ccs.tencentyun.com --username=200025387639
      # Push the Docker image to TKE Registry
      - name: Publish
        run: |
          docker push ${TKE_IMAGE_URL}:${GITHUB_SHA}

      - name: Set up Kustomize
        run: |
          curl -o .deploy/kustomize --location https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x .deploy/kustomize

      - name: Set up ~/.kube/config for connecting TKE cluster
        uses: TencentCloud/tke-cluster-credential-action@v1
        with:
          secret_id: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
          secret_key: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
          tke_region: ${{ env.TKE_REGION }}
          cluster_id: ${{ env.TKE_CLUSTER_ID }}

      - name: Replace API server
        run: |
          kubectl config set clusters.${TKE_CLUSTER_ID}.server ${TKE_CLUSTER_IP}

      - name: Switch to TKE context
        run: |
          kubectl config use-context ${TKE_CLUSTER_ID}-context-default

      # Deploy the Docker image to the TKE cluster
      - name: Deploy
        run: |
          cd .deploy
          echo ${TKE_IMAGE_URL}:${GITHUB_SHA}
          ./kustomize edit set image ${TKE_IMAGE_URL}:${GITHUB_SHA}
          ./kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/${DEPLOYMENT_NAME}
          kubectl get services -o wide
